# Generated by Django 5.2.3 on 2025-08-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_likes_delete_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
