# Generated by Django 5.1.1 on 2024-10-10 07:27

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
